navikt/aktivitetsplan

- package-lock.json
- package.json
- test/nightwatch-tester/integration/date-utils.js
2.18.1 har en security vulnerable dependency
bumping to newest version
> KAIZEN-0: Bump moment

- example/index-utside.html
- example/mocks/index.js
- example/mocks/mal.js
fikset linken til css på utsiden
fikset mal mock på utsidem
> [KAZEN-0] fikser mokken

- src/moduler/aktivitet/visning/underelement-for-aktivitet/underelementer-for-aktivitet.js
- src/utils/getScrollParent.js
Når man åpnger dialog/historikk visningen i et aktivitetskort så
skal man scrolle disse visningene inn i viewet tilb brukeren
> FO-311: Scroll til dialog/historikk når åpnet

- package.json
- test/nightwatch-tester/conf/browserstack.conf.js
- test/nightwatch-tester/integration/getNetworkIp.js
- test/nightwatch-tester/integration/globals.js
Må bruke ip for å få lastet inn aktivitetsplan på ios11
> FO-1063: Browserstack test pa ios11

- src/moduler/brodsmuler/brodsmuler.js
Jeg fikser jeg en warning Izis viste meg, pluss at jeg foreløpig fjerner fjerningen av Veien til arbeid-brødsmulen inntil vi har funnet ut av det. Dermed vil ikke bruker merke noen forskjell hvis denne blir prodsatt. De eneste andre nåværende endringene i master er også fra FO-961.
> FO-961 Fiks warning + ikke skjul veien til arbeid

- src/app.js
- src/provider.js
- src/reducer.js
> Opprett ny redux store ved endring av fnr istede for å resette den eksisterende

- example/mocks/index.js
- example/mocks/utils.js
- src/felles-komponenter/dropdown/dropdown.js
- src/hovedside/tavle/aktivitetstavle.js
- src/moduler/oppfolging-status/oppfolging-api.js
Kallet ble tidligere gjort av veilarbpersonfs, men etter bytting til mao
så gjøres ikke kallet. Dette hører nok uansett mer hjemme i
aktivitetsplanen, så legger det til her fremfor mao
> Les aktivitetsplan

- example/mocks/oppfolging.js
- src/moduler/innstillinger/avslutt-oppfolging/avslutt-oppfolging-prosess.js
- src/moduler/innstillinger/avslutt-oppfolging/avslutt-oppfolginsperiode.js
når en prøver å avslutte oppfølging
> [FO-1392] legger til alertstripe hvis bruker har aktive tiltak i arena

- src/felles-komponenter/utils/lenkeknapp.js
- src/felles-komponenter/utils/lenkeknapp.less
- src/moduler/aktivitet/visning/aktivitetvisning-container.js
- src/moduler/aktivitet/visning/aktivitetvisning.js
- src/moduler/aktivitet/visning/hjelpekomponenter/aktivitetinformasjon-visning.js
- src/moduler/verktoylinje/verktoylinje.js
- test/integration/pages/aktivitetsvisningModal.js
Skal ikke kunne endre aktiviteten mens man venter på en endring skjer
> KAIZEN-0: Disable endre link når aktivitet laster

- src/moduler/aktivitet/visning/underelement-for-aktivitet/underelementer-for-aktivitet.js
ScrollTo does not exists in IE. Also only scroll if some of the
elements are shown. Not all the time
> KAIZEN-0: Use scrollTop instead of scrollTo

- package-lock.json
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-referat-form.js
Med den nye api forandringen så får vi versjonskonflikt hvis dette
ikke er gjort
> KAIZEN-0: Bruk res i oppdater ref for pub referat

- Dockerfile.e2e
- test/integration/run-test.sh
Script for å kunne bestemme om tester skal kjøre mot testmiljø
> Verdikjedetest docker

- src/environment.js
> KAIZEN-0: Use the new API

- app-config-fss.yaml
- app-config-sbs.yaml
> KAIZEN-0: Update nais yaml

- example/mocks/mal.js
- src/felles-komponenter/feature/feature.js
- src/hovedside/hovedside.js
- src/hovedside/maalLinje/mitt-maal.js
- src/moduler/aktivitet/aktivitet-forms/lagre-aktivitet.js
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort.js
- src/moduler/aktivitet/visning/aktivitetvisning-container.js
- src/moduler/aktivitet/visning/aktivitetvisning.js
- src/moduler/aktivitet/visning/etikett-oppdatering/oppdater-aktivitet-etikett.js
- src/moduler/aktivitet/visning/hjelpekomponenter/aktivitetinformasjon-visning.js
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-aktivitet-status.js
- src/moduler/feilmelding/private-feilmelding.js
- src/moduler/mal/aktivitetsmal-form.js
- src/moduler/mal/aktivitetsmal.js
- src/moduler/privat-modus/privat-modus-selector.js
- src/moduler/verktoylinje/verktoylinje.js
- tekster/nb/private.advarsel_nb.txt
- tekster/nb/private.forstatt_nb.txt
- tekster/nb/private.info.1_nb.txt
- tekster/nb/private.info.2_nb.txt
- tekster/nb/private.info.3_nb.txt
- tekster/nb/private.info.4_nb.txt
- tekster/nb/private.info.header_nb.txt
Altid vis en advarsel til brukere i som er i privat modus
Planen skal ikke lengre kunne forandres av disse. Kun leses.
I fremtiden så skal privat modus helt vekk og denne koden slettes
> FO-1562: Skru av privat modus

- src/felles-komponenter/modal/modal.js
- src/moduler/aktivitet/aktivitet-routes.js
- src/moduler/aktivitet/visning/aktivitetvisning-container.js
- src/moduler/aktivitet/visning/avtalt-container/avtalt-form.js
- src/moduler/aktivitet/visning/etikett-oppdatering/stilling-etikett-form.js
- src/moduler/aktivitet/visning/status-oppdatering/aktivitet-status-form.js
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-referat-form.js
- src/moduler/aktivitet/visning/underelement-for-aktivitet/underelementer-for-aktivitet.js
- src/moduler/arbeidsliste/arbeidsliste-container.js
- src/moduler/arbeidsliste/arbeidsliste-legg-til-form.js
- src/moduler/arbeidsliste/arbeidsliste-rediger-form.js
- src/moduler/dialog/dialog-modal/dialog-henvendelse.js
- src/moduler/dialog/dialog-modal/dialog-modal.js
- src/moduler/dialog/dialog-modal/dialog.js
- src/moduler/innstillinger/avslutt-oppfolging/avslutt-oppfolginsperiode.js
- src/moduler/innstillinger/innstillinger-modal.js
- src/moduler/innstillinger/opprett-oppgave/opprett-oppgave.js
- src/moduler/innstillinger/sett-digital-oppfolging/sett-digital-oppfolging.js
- src/moduler/innstillinger/sett-manuell-oppfolging/sett-manuell-oppfolging.js
- src/moduler/innstillinger/start-eskalering/start-eskalering.js
- src/moduler/innstillinger/start-kvp-periode/start-kvp-periode.js
- src/moduler/innstillinger/stopp-eskalering/stopp-eskalering.js
- src/moduler/innstillinger/stopp-kvp-periode/stopp-kvp-periode.js
- src/moduler/mal/aktivitetsmal-form.js
- src/moduler/mal/aktivitetsmal-modal.js
- tekster/nb/aktkivitet-skjema.lukk-advarsel_nb.txt
Gjør så man kan trykke utenfor modal for å lukke den.
Hvis det er endringer i formet får man opp en alert-box som sier ifra.
> Fo 1484 ulagrede endringer

- src/moduler/aktivitet/aktivitet-util.js
Av og til så er serveren raskere enn fronteden på moment().now
> FO-1773: Legg på en fremover endrings delay

- example/mocks/aktivitet.js
- src/hovedside/hovedside.js
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort.js
- src/moduler/aktivitet/aktivitet-util.js
- src/moduler/informasjon/informasjon-henting.js
- src/moduler/oppfolging-status/oppfolging-status.js
- src/moduler/oppfolging-status/videre-send-bruker-eller-render-children.js
Ikke hent les/vis les hvis bruker ikke er under oppfolging
> KAIZEN-0: Bedre håndtering at les er nede

- src/moduler/oppfolging-status/oppfolging-status.js
- src/moduler/oppfolging-status/videre-send-bruker-eller-render-children.js
Ikke vis vilkår til personer som ikke er underOppfolging
> KAIZEN-0: Fjern lest stuff som ikke er i bruk

- src/app.js
> KAIZEN-0: Create history in render

- src/moduler/aktivitet/ny-aktivitet/ny-aktivitet.js
- src/moduler/aktivitet/ny-aktivitet/ny-aktivitet.less
Skiller mer på veileders og brukers linker
> KAIZEN-0: Grupper ny aktivitet linker etter bruk

- package-lock.json
- package.json
- src/hovedside/hovedside.js
- src/hovedside/hovedside.less
- src/main.less
- src/moduler/varslinger/varslinger.js
- src/vendors.less
> KAIZEN-0: Fjern nav-grid

- package-lock.json
- package.json
- src/felles-komponenter/aktivitet-etikett/aktivitet-etikett.js
- src/felles-komponenter/aktivitet-etikett/aktivitet-etikett.less
- src/felles-komponenter/dato.js
- src/moduler/aktivitet/aktivitet-actions.js
- src/moduler/aktivitet/aktivitet-forms/stilling/aktivitet-stilling-form.js
- src/moduler/aktivitet/aktivitet-kort/Soknadsfrist.jsx
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort-periode.js
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort.js
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort.less
- src/moduler/aktivitet/visning/detaljer/stilling-detaljer.js
- src/moduler/utskrift/aktivitetsplanprint.js
- src/utils.js
- src/utils.test.js
- tekster/nb/stilling-aktivitet-form.label.til-dato_nb.txt
- Frist skal ikke være påkrevd når man oppretter stillingskort
- Vise søknadsfrist på stillingskort når bruker ikke har lagt på etiketter.
- Teksten skal være rød+italic når fristen nærmer seg.
- Stillingskort skal ikke vise den vanlige Periodevisningen
- Slette ubrukt kode
> FO-1985: Vise søknadsfrist på stillingskort

- src/mocks/demo/demoDashboard.js
- src/mocks/demo/sessionstorage.js
- src/mocks/features.js
> [FO-2364] mulighet til å togle feature togles for mock

- src/mocks/demo/demoDashboard.js
- src/mocks/demo/hurtigfilter.js
- src/mocks/demo/sessionstorage.js
- src/mocks/oppfolging.js
- src/moduler/utskrift/printmelding.js
Legg på manuell bruker flagget i mock dashboard
> KAIZEN-0: Fjern redux-form i print

- src/felles-komponenter/skjema/input-v2/textarea.js
- src/moduler/mal/aktivitetsmal-endre.js
- src/moduler/mal/aktivitetsmal-form.js
- src/moduler/mal/aktivitetsmal-modal.js
- src/moduler/mal/aktivitetsmal.js
Mal skal flyttes ut etterhvert. Så denne koden er ikke refaktorert
skikkelig.
Fjernet også isDirty sjekken her siden dette skal snart ikke lengre
være i bruk
> KAIZEN-0: Fjern redux-form i mal

- src/moduler/aktivitet/aktivitet-forms/stilling/aktivitet-stilling-form.js
- src/utils.js
setter dagens dato som deafult verdi for stillingskortet
> [KAIZEN-0] deafult verid for fra dato stillingskort

- src/moduler/mal/aktivitetsmal.js
Retter feil som fra min forrige PR
> FO-2485: Retter feil

- package-lock.json
- src/moduler/aktivitet/visning/avtalt-container/avtalt-form.js
- src/moduler/aktivitet/visning/forhandsorientering/forhandsorientering-form.js
- src/moduler/aktivitet/visning/hjelpekomponenter/statusadministrasjon.js
Gitt at en veileder lager en arena aktivitet
så skal forhåndsorientering bli satt på aktiviteten likt som forhåndsorientering blir på andre avtalt med nav aktiviteter.
Forhåndsorientering skal likevel kunne sendes flere ganger på arena aktiviteten, likt som det var tidligere. 
> FO-2479: Skru på forhåndsorientering på arena akt

- src/moduler/dialog/dialog-modal/henvendelser.js
componentWillReceiveProps er deprecated.
> KAIZEN-0: Fjern componentWillReceiveProps

- package-lock.json
- src/app.js
- src/felles-komponenter/hooks/useEventListner.ts
- src/moduler/aktivitet/aktivitetliste-selector.js
fikser vis aktiivitet med id i fiel periode
> [FO-2680] evnt lenke fra ny dialog til aktivitet inside.

- src/felles-komponenter/ekspanderbar-linje/ekspanderbar-linje.module.less
- src/moduler/aktivitet/visning/endre-linje/endre-linje.js
- src/moduler/aktivitet/visning/endre-linje/endre-linje.module.less
- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogLenkeInnhold.tsx
> [FO-2552] setter riktig pointer på knappene

- src/app.js
- src/moduler/aktivitet/aktivitet-action-types.js
- src/moduler/aktivitet/aktivitet-reducer.js
- src/moduler/dialog/dialog-reducer.js
- src/moduler/oppfolging-status/oppfolging-reducer.js
- src/utils/UpdateHandler.tsx
lager listener og diaptcher for window events
> [FO-2721] komunikasjon mellom flatene

- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogIkon.tsx
- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogLenkeInnhold.tsx
- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/dialogunderelement.module.less
tekst endring ved uleste dialoger
> [KAIZEN-0] uleste dialoger ikon tekst størlse fiks

- package-lock.json
- package.json
- src/moduler/dialog/dialog-modal/ny-henvendelse.js
> FO-2801: Legg til info om svartid pga korona

- src/moduler/aktivitet/aktivitet-forms/samtalereferat/samtalereferat-form.js
- src/moduler/aktivitet/visning/referat/oppdater-referat-form.js
- src/moduler/aktivitet/visning/referat/oppdater-referat.less
- src/moduler/aktivitet/visning/referat/referat-visning.js
https://jira.adeo.no/browse/FO-2826
> FO-2826: Småfiks Aktivitetsplan

- package-lock.json
- package.json
- src/moduler/utskrift/print/filter-utils.test.tsx
- src/moduler/utskrift/print/filter-utils.tsx
- src/moduler/utskrift/print/print.tsx
Flytter koden som var der inn i ny fil for å rydde og fikser datosammenlikning
> FO-3003: Fikser feil i utskrift når man har KVP periode

- src/moduler/aktivitet/etikett/SokeStatusEtikett.tsx
- src/moduler/aktivitet/visning/endre-linje/endre-linje.module.less
- src/moduler/aktivitet/visning/etikett-oppdatering/StillingEtikettForm.tsx
- src/moduler/aktivitet/visning/etikett-oppdatering/oppdater-aktivitet-etikett.js
https://trello.com/c/5Y0Hi0ob/61-etiketttekst-sendt-s%C3%B8knad-og-venter-p%C3%A5-svar
> Endre etikett-tekst i detaljert visning av aktivitet og fikse styling

- src/moduler/aktivitet/visning/aktivitetvisning.less
> Etiketter skal ha uppercase i aktivitetskort både på ekstern og intern flate.

- package-lock.json
- src/moduler/aktivitet/aktivitet-kort/AktivitetskortPeriode.tsx
https://trello.com/c/gfO4lhFr/151-capslock-p%C3%A5-fra
> Fix: ikke ha fra og til i capslock på aktivitetskort

- src/felles-komponenter/LinkAsDiv.tsx
- src/felles-komponenter/utils/Lenkeknapp.tsx
- src/moduler/aktivitet/aktivitet-kort/Aktivitetskort.tsx
- src/moduler/aktivitet/aktivitet-kort/Aktivitetstype.tsx
- src/moduler/verktoylinje/verktoylinje.js
https://trello.com/c/76F8nqDF/46-uu-fiks
> Fikse VoiceOver for lenker + smårydding

- src/moduler/aktivitet/visning/avtalt-container/AvtaltForm.tsx
- src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsMelding.tsx
- src/moduler/aktivitet/visning/avtalt-container/KanIkkeSendeForhaandsorienteringInfotekst.tsx
- src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltInfotekst.tsx
- src/moduler/aktivitet/visning/avtalt-container/VarslingInfo.tsx
- src/moduler/filtrering/filter/FilterVisning.tsx
- src/moduler/filtrering/filter/avtalt-filter.js
- src/moduler/filtrering/filter/etikett-filter.js
- src/moduler/filtrering/filter/status-filter.js
- src/moduler/filtrering/filter/type-filter.js
Har i tillegg fikset warningen som klaget på at det manglet `key` i rendrede children
https://trello.com/c/oVatPN8u/128-del1-endringer-veileder
> Ny fho: Småfiks og tekstendringer

- src/moduler/aktivitet/visning/avtalt-container/AvtaltForm.module.less
- src/moduler/aktivitet/visning/avtalt-container/AvtaltForm.tsx
- src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsMelding.module.less
- src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsMelding.tsx
- src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltInfotekst.tsx
- src/moduler/aktivitet/visning/avtalt-container/VarslingInfo.module.less
- src/moduler/aktivitet/visning/avtalt-container/VarslingInfo.tsx
Endringer fra kommentaren i denne oppgaven:
https://trello.com/c/oVatPN8u/128-del1-endringer-veileder
> Småfiks av luft og tekst for ny FHO

- src/moduler/filtrering/filter/FilterCheckbox.tsx
- src/moduler/filtrering/filter/FilterVisning.tsx
https://trello.com/c/4uuOHBJ1/211-aktivitetsplan-sm%C3%A5fiks
> Fikse unkontrollert endring i filtercheckbox

- src/moduler/aktivitet/visning/hjelpekomponenter/detaljvisning-lenke.js
> Aktivitetslenker: Åpne i ny fane, fikset tilbakemelding fra test

- src/moduler/mal/MalForm.tsx
- src/moduler/mal/mal-container.tsx
- src/moduler/mal/mal-historikk.tsx
- src/moduler/mal/mal-modal.tsx
- src/moduler/mal/mal.tsx
> Small fixes ready for development

- src/moduler/mal/mal-container.tsx
> Fikset feil hvor man fikk popup selvom man hadde trykket lagre

- nais-q-sbs.yaml
Mulig det er mer som må gjøres for at det skal funke
> Legger inn ingress for å kunne teste med naisdevice

- src/felles-komponenter/EkspanderbartTekstomrade.module.less
- src/felles-komponenter/EkspanderbartTekstomrade.tsx
- src/mocks/aktivitet.js
https://jira.adeo.no/browse/FAGSYSTEM-165599
> HOTFIX: Manglende avsnitt og linjeskift når samtalereferat vises.

- src/moduler/verktoylinje/navigasjonslinje.module.less
Småfikser etter tilbakemelding på https://trello.com/c/wqpQDkaN
> Bedre wrapping på veldig små skjermer, og større sidetittel

- tekster/nb/aktivitetkort.dato_label_nb.txt
- tekster/nb/aktivitetstatus.oppdater-status-begrunnelse_nb.txt
- tekster/nb/aktivitetvisning.header_nb.txt
- tekster/nb/endringstype.ETIKETT_ENDRET_nb.txt
- tekster/nb/endringstype.STATUS_ENDRET_nb.txt
- tekster/nb/sett-avtalt-bekreftelse_nb.txt
- tekster/nb/sett-avtalt-forhandsrientering-bruker-uten-aktivitesplan_nb.txt
Fallback (other) ved 'select' ser ut til å være påkrevd i ny versjon 
https://trello.com/c/n1I576Eg
> Fikse tekster etter intl-oppgradering

- src/moduler/aktivitet/visning/avtalt-container/arena-aktivitet/ForhaandsorienteringForm.tsx
- src/moduler/aktivitet/visning/forhandsorientering-gammel/ForhandsorienteringForm.jsx
- src/moduler/aktivitet/visning/referat/oppdater-referat-form.js
Dette er regresjoner etter oppgradering av use-formstate
https://trello.com/c/Fu80VTP4
> useFormstate validering må returnere undefined eller ingenting ved validering ok

- src/moduler/aktivitet/visning/avtalt-container/aktivitet/KanIkkeSendeForhaandsorienteringInfotekst.tsx
En forbedring av løsning for https://trello.com/c/l781OMS6
> Endret rekkefølge på fho infotekst sjekker

- src/mocks/aktivitet.js
- src/moduler/aktivitet/visning/versjoner/versjonTekster.ts
Mindre ting som dukker opp under testing av historikk
> Småfeil oppdaget ved testing

- src/datatypes/aktivitetTypes.ts
- src/mocks/aktivitet.js
- src/moduler/aktivitet/visning/avtalt-container/utilsForhaandsorientering.ts
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/Forhaandsorienteringsvisning.tsx
- src/moduler/utskrift/print/aktiviteter/AktivitetPrint.tsx
ref denne som er deployet til test: https://github.com/navikt/veilarbaktivitet/pull/172
feltet er renamet
> Renamer lestfelt for å unngå forvirring på om det er bool/dato

- src/moduler/aktivitet/visning/hjelpekomponenter/detaljvisning-lenke.tsx
Forsøk på å fikse feil av type https://trello.com/c/O4QT3tPf
> Trim lenke for å unngå encodet space character i url

- src/moduler/aktivitet/visning/avtalt-container/aktivitet/AvtaltForm.tsx
- src/moduler/aktivitet/visning/avtalt-container/aktivitet/AvtaltFormContainer.tsx
- src/moduler/aktivitet/visning/avtalt-container/aktivitet/KanIkkeSendeForhaandsorienteringInfotekst.tsx
> Ny melding ved forhåndsorientering når tilDato mangler

- src/moduler/aktivitet/aktivitet-kort/Aktivitetskort.tsx
- src/moduler/aktivitet/aktivitet-kort/Aktivitetstype.tsx
- src/moduler/aktivitet/visning/AktivitetvisningModal.tsx
- src/moduler/aktivitet/visning/status-oppdatering/status-visning.js
- src/moduler/aktivitet/visning/versjoner/versjonTekster.ts
- src/moduler/filtrering/filter/FilterCheckbox.tsx
- src/moduler/filtrering/filter/FilterVisning.tsx
- src/moduler/filtrering/filter/avtalt-filter.js
- src/moduler/filtrering/filter/etikett-filter.js
- src/moduler/filtrering/filter/status-filter.js
- src/moduler/filtrering/filter/type-filter.js
- src/moduler/utskrift/print/aktiviteter/AktivitetPrint.tsx
- src/utils/textMappers.ts
Rydder litt, koden som mapper til tekster for aktivitetstype var duplisert mange steder
> Samler implementasjon for uthenting av tekst for aktivitetstype

- src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltInfotekst.tsx
- src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltVisning.tsx
> Korrekt feedbackmelding når 'avtalt med nav' aktivitet mangler tilDato

- nais-q-sbs.yaml
https://trello.com/c/BRTMX0YJ/214-flytte-aktivitetsplan-url-og-hode-fot
> Legger til ingress som kan funke med ny decorator

- package-lock.json
- src/moduler/aktivitet/visning/AktivitetvisningIkkeFunnet.module.less
- src/moduler/aktivitet/visning/AktivitetvisningIkkeFunnet.tsx
- src/moduler/aktivitet/visning/aktivitetvisning-container.js
https://trello.com/b/L3FK29Ec/team-dab
> Lagt til Feilhåndtering av visning av aktivitet som ikke finnes

- src/api/aktivitetAPI.ts
- src/datatypes/aktivitetTypes.ts
- src/mocks/aktivitet.js
- src/moduler/aktivitet/aktivitet-actions.js
- src/moduler/aktivitet/visning/dele-cv/DeleCvContainer.tsx
- src/moduler/aktivitet/visning/detaljer/StillingFraNavDetaljer.tsx
- src/moduler/aktivitet/visning/detaljer/aktivitetsdetaljer.js
- src/moduler/aktivitet/visning/hjelpekomponenter/AktivitetinformasjonVisning.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/CustomAlertstripe.module.less
https://trello.com/c/1puwfP82/327-gj%C3%B8re-det-mulig-for-bruker-%C3%A5-svare-p%C3%A5-om-cv-skal-deles
https://trello.com/c/omyZYt2R/263-lage-ny-type-aktivitet-for-rekrutteringsbistand
> Fikser feil etter testing av deleCV svar

- src/datatypes/aktivitetTypes.ts
- src/mocks/aktivitet.js
- src/moduler/aktivitet/visning/detaljer/KontaktInfoDetaljer.tsx
- src/moduler/aktivitet/visning/detaljer/StillingFraNavDetaljer.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/Informasjonsfelt.tsx
> Kontaktinfo på stilling-fra-nav kort

- src/mocks/aktivitet.js
- src/moduler/aktivitet/aktivitet-kort/AktivitetskortTillegg.tsx
- src/moduler/aktivitet/ikke-delt-ferdig-markering/IkkeDeltFerdigMarkering.tsx
- src/moduler/aktivitet/ikke-svart-markering/IkkeSvartMarkering.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/AktivitetinformasjonVisning.tsx
> 'Ikke svart'-markering på kortene

- src/datatypes/aktivitetTypes.ts
- src/mocks/aktivitet.js
- src/moduler/aktivitet/visning/versjoner/versjonTekster.ts
> historikk for del-cv

- src/moduler/aktivitet/visning/dele-cv/DeleCvContainer.tsx
- src/moduler/aktivitet/visning/dele-cv/tekster.ts
- src/moduler/aktivitet/visning/versjoner/versjonTekster.ts
https://nav-it.slack.com/archives/C01TZF6CUJE/p1632388041052300?thread_ts=1632382743.042700&cid=C01TZF6CUJE
Feil i tekst på aktivitetskortet. 
Du bestemmer selv
Feil tekst på knappene (arbeidsgiver / arbeidsgiveren)
> Mindre tekstrettinger

- src/moduler/aktivitet/aktivitet-kort/AktivitetskortPeriode.tsx
- src/moduler/aktivitet/aktivitet-kort/aktivitetkort-periode.test.js
> ikke vis periode hvis stilling fra nav

- src/moduler/informasjon/informasjon-modal.js
- src/moduler/informasjon/informasjon.less
> flytt video til bunnen

- src/index.less
> fiks utskrift av aktivitetsplan

- .github/workflows/build.yml
- .github/workflows/deploy-test.yml
- nais-fss.yaml
- nais-q-fss.yaml
- nais-q-sbs.yaml
- nais-sbs.yaml
Reverts navikt/aktivitetsplan#864
> Revert "Flutte fra default til pto namespace"

- src/moduler/aktivitet/visning/detaljer/StillingFraNavDetaljer.tsx
- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogLenke.tsx
- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogLenkeInnhold.tsx
> skjul kontaktinfo på stilling fra nav kort

- src/moduler/aktivitet/visning/underelement-for-aktivitet/dialog/DialogLenkeInnhold.tsx
> endre tekst tekst på dialog

- src/moduler/aktivitet/visning/dele-cv/MeldInteresseForStilling.tsx
- src/utils/dateUtils.ts
> Svar på vegne av bruker dato

- .github/workflows/gcp-root.yml
> Workflow setup gcloud

- nais/dev-ekstern.yaml
- nais/dev-intern.yaml
- nais/prod-ekstern.yaml
- nais/prod-intern.yaml
TODO hente inn nytt pto-frontend image
> Ny loginservice discovery url dev ekstern

- src/constant.js
- src/datatypes/aktivitetTypes.ts
- src/mocks/aktivitet.js
- src/mocks/fixtures/stillingFraNavFixtures.js
- src/moduler/aktivitet/etikett/StillingFraNavEtikett.tsx
- src/moduler/aktivitet/visning/soknadsstatus-oppdatering/OppdaterSoknadsstatus.tsx
- src/moduler/aktivitet/visning/soknadsstatus-oppdatering/SoknadsstatusForm.tsx
- src/moduler/aktivitet/visning/versjoner/Endringstekst.tsx
- src/utils/textMappers.ts
for at Stilling fra Nav-aktivitet har status Ikke fått jobben
> Grafiske endringer 

- package-lock.json
- package.json
- src/felles-komponenter/skjema/datovelger/Datovelger.tsx
blir fortsatt dratt inn av nav-datovelger, men blir borte når vi går over til nytt designsystem :)
> fjern dayjs

- tekster/nb/aktivitet.etikett.cv_delt_nb.txt
- tekster/nb/aktivitet.etikett.ikke_fatt_jobben_nb.txt
- tekster/nb/aktivitet.etikett.venter_nb.txt
feil i prod akk. nå. quick fix
> fix stillingsstatus filtertekst

- nais/dev-intern.yaml
Ref: https://nav-it.slack.com/archives/CQ2H1AY3Z/p1678198147308709?thread_ts=1678095853.805939&cid=CQ2H1AY3Z
> Fikse CORS-feil etter endring av dev-ingress

- src/felles-komponenter/skjema/datovelger/ControlledDateRangePicker.tsx
- src/moduler/aktivitet/aktivitet-forms/stilling/AktivitetStillingForm.tsx
> temp fix datepicker

- .env.dev-ekstern
- .env.local
- src/moduler/aktivitet/avslutt/FullforAktivitet.tsx
> fiks arbeidssøkerregistrering dev lenke

- .github/workflows/deploy-ekstern.yml
- .github/workflows/deploy-intern.yml
- .github/workflows/gh-pages.yml
- .github/workflows/prettier.yml
- .github/workflows/test.yml
- package-lock.json
- package.json
- src/amplitude/amplitude.ts
- src/amplitude/taxonomy-events.ts
- src/moduler/aktivitet/aktivitet-forms/samtalereferat/InnerSamtalereferatForm.tsx
- src/moduler/aktivitet/visning/referat/OppdaterReferatForm.tsx
språksjekk + amplitudemetrikker
https://unleash.nais.io/#/features/strategies/aktivitetsplan.vis-spraksjekk
> språksjekk + amplitudemetrikker

- .github/workflows/deploy-ekstern.yml
- .github/workflows/deploy-feature-branch.yml
- .github/workflows/deploy-intern.yml
- .github/workflows/deploy.yml
- Legg til secret eksplisitt i templates
- Invalidate cache in github action
> Workflow upgrades

- .github/workflows/test.yml
Reverts navikt/aktivitetsplan#1162
> Revert "logg-feil"

- nais/dev-ekstern.yaml
- nais/prod-ekstern.yaml
Denne hang igjen, så jeg bare fjernet den.
> Fjern outbound rule for poao-unleash

- src/amplitude/amplitude.ts
- src/amplitude/taxonomy-events.ts
- src/moduler/aktivitet/ny-aktivitet/NyAktivitetForm.tsx
- src/moduler/aktivitet/rediger/EndreAktivitet.tsx
Har vært rapportert mye bugs med lukking av samtalereferat og møte med nav og tekst som forsvinner så legger til tracking av hvor ofte modalene lukkes og om de har endringer som ikke er lagret (isDirty)
> Legg til lukking av modal i amplitude
