- src/felles-komponenter/modal/modal-header.js
- src/felles-komponenter/tall-alert.js
- src/felles-komponenter/tall-alert.less
- src/moduler/aktivitet/aktivitet-kort/aktivitetskort-tillegg.js
Viser seg at .kun-for-skjermleser gir visningsfeil i drag & drop
for noen browsere. .sr-only løser problemet og kommer fra felles
bibloteket
> KAIZEN-0: bruk .sr-only

- app-config-fss.yaml
This change sets sensible values for request/limit on both cpu and memory
based upon metrics observed in production
See:
https://grafana.adeo.no/d/000000283/nais-app-dashboard?refresh=5s&orgId=1&from=now-90d&to=now&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-app=aktivitetsplan-fss&var-namespace=All&var-docker_image=3470.20180613.1627&var-environment=default
> Adjust resource request and limits(fss)

- app-config-sbs.yaml
This change sets sensible values for request/limit on both cpu and memory 
based upon metrics observed in production
See:
https://grafana.adeo.no/d/000000283/nais-app-dashboard?refresh=5s&orgId=1&from=now-90d&to=now&var-interval=$__auto_interval_interval&var-datasource=prod-sbs&var-app=aktivitetsplan&var-namespace=All&var-docker_image=3571.20180816.1301&var-environment=default
> Adjust nais resource request and limits

- example/mocks/oppfolging.js
- src/moduler/oppfoelgingsstatus/oppfoelgingsstatus-selector.js
- src/moduler/oppfolging-status/oppfolging-selector.js
- src/moduler/varslinger/varsel-alertstriper.js
- src/moduler/varslinger/varslinger.js
- tekster/nb/oppfolging.ikke-under-oppfolging.reaktiveres.lenke-tekst_nb.txt
- tekster/nb/oppfolging.inaktivert-28-til-10-dager.reaktiveres_nb.txt
- tekster/nb/oppfolging.inaktivert-mer-enn-28-dager.reaktiveres_nb.txt
- tekster/nb/oppfolging.inaktivert-mindre-enn-10-dager.reaktiveres_nb.txt
Akseptansekriterier
Gitt at bruker er i aktivitetsplan og har vært inaktiv i mindre enn 28 dager og det er mellom 28-10 dager igjen
    a) så skal jeg se en alertstripe advarsel med teksten "Du er ikke lenger registrert hos NAV. Hvis du fortsatt skal motta ytelser, få oppfølging fra NAV og bruke aktivitetsplanen må du være registrert. Gå til registrering" 
     b) så skal jeg kunne klikke på "gå til registrering" som er en lenke som fører meg til reaktivering
Gitt at bruker er i aktivitetsplan og har vært inaktiv i mindre enn 28 dager og det er færre enn 10 dager igjen
    a) så skal jeg se en alertstripe advarsel med teksten "Du er ikke lenger registrert hos NAV. Hvis du fortsatt skal motta ytelser, få oppfølging fra NAV og bruke aktivitetsplanen må du være registrert. Om x dager vil …
> Fo 1295 infotekst til inaktivert brukere

- src/moduler/aktivitet/aktivitet-api.js
- src/moduler/aktivitet/aktivitet-referat-reducer.js
Dette er både for å forenkle api-et og for å sjekke at vi ikke får
versjonskonflikt når endringen skjer
> KAIZEN-0: Send aktiviteten når den publiseres

- src/moduler/dialog/dialog-modal/henvendelser.js
For at veilarbpersonflatefs skal få vite når dialoger blir lest, så må det legges på et event når det blir gjort kall mot /les i veilarbdialog
> FO-2013 La til event når dialog blir lest

- public/index.html
- src/index.js
- src/mocks/aktivitet.js
- src/mocks/appconfig.js
- src/mocks/demoDashboard.js
- src/mocks/dialog.js
- src/mocks/mal.js
- src/mocks/me.js
- src/mocks/oppfolging.js
- src/mocks/sessionstorage.js
- Brukergrensesnitt for å velge mellom veileder/eksternbruker og privat modus eller under oppfølging
- Endringer lagres i session storage (default er eksternbruker under oppfølging)
Mangler:
- Styling
- "Ny bruker" innstilling med automatisk oppretta aktiviteter
> FO-2241: demodashbord hvor man kan bytte brukertype og modus

- package-lock.json
- src/felles-komponenter/skjema/input-v2/checkbox.js
- src/mocks/oppfoelgingsstatus.js
- src/moduler/aktivitet/visning/forhandsorientering/forhandsorientering-form.js
- src/moduler/aktivitet/visning/hjelpekomponenter/statusadministrasjon.js
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-referat-container.js
Gjelder bare arena aktiviteter
Vi må vurdere nå om vi skal fjerne koden som omgår oppfoelgingsstatus
Dette er ikke lengre i bruk nå, men vi må høre med produkteier om vi kan bare slutte å bruke statusen for å vise forhåndsorienteringer for arena aktiviteter
> KAIZEN-0: Fjern redux-form i forhåndsorientering

- src/moduler/aktivitet/visning/endre-linje/endre-linje.js
- src/moduler/aktivitet/visning/etikett-oppdatering/oppdater-aktivitet-etikett.js
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-aktivitet-status.js
På aktivitetskort som ligger i fullført og avbryt
Så skal “endre”-knappen (på status og søknadsprosess-status) skjules (en
Fiksaton
> KAIZEN-0: Ikke vis endre ved fullført/avbrutt

- src/moduler/aktivitet/aktivitet-forms/mote/mote-aktivitet-form.js
- src/moduler/aktivitet/aktivitet-forms/mote/mote-aktivitet-form.test.js
- src/moduler/aktivitet/aktivitet-util.test.js
- src/moduler/aktivitet/aktivitet-util.ts
Gitt at veileder er inne på en møteaktivitet
så skal jeg se et inputfelt der en kan skrive inn klokkeslettet med kolon i mellom 09:35 (se feks ruter.no for inspirasjon) bruke html-inputtime ?   Foreslår at det er mulig å velge hvert 5. minutt (med html-step-attributten) ELLER gjøre slik google calendar med dropdown+skrivemulighet (se bilde)?
så skal jeg se et inputfelt med validering der jeg kan skrive inn varighet i antall minutter
> Møte: klokkeslett og varighet

- src/moduler/mal/mal-visning.tsx
- src/moduler/mal/mal.tsx
**Gitt at** bruker ikke er under oppfølging så skal teksten si at målet er satt i en tidligere periode(ref FO-2456)
**Gitt at** bruker ikke skal kunne endre mål og ikke har gjeldende må(privat bruker) så skal appen ikke krasje og det skal vises tekst som sier at det ikke har blitt skrevet mål i denne perioden.
> FO-2984: retter feil for brukere som ikke har mal satt

- src/mocks/aktivitet.js
- src/mocks/demo/demoDashboard.js
- src/mocks/demo/sessionstorage.js
- src/mocks/failOrGetResponse.tsx
- src/mocks/index.js
- src/mocks/oppfolging.js
Gjør det mulig å teste situasjoner hvor backendkall feiler.
Alle kall mot samme backend bruker samme innstilling i demomocken(unntatt arenaaktiviteter som er separat fordi dette er et eget scenario i brukerhistorien)
Man kan teste at GET på aktivitet feiler ved å krysse av for "aktivitet feiler" og gå direkte til url for en aktivitet.
Enn så lenge så ser jeg ikke behov for å trenge å finjustere mer hvilke kall som feiler men gi beskjed om du mener noe annet
> FO-2927: Implementerer mocker for feilsituasjoner

- src/moduler/aktivitet/visning/detaljer/behandlings-detaljer.js
Ikke sikker på om løsning er korrekt. Ser ikke helt hvordan styling og css klasser brukes for å styre visning, så løsningen er en ganske eksplisitt fix direkte på BehandlingsDetaljer komponenten.
> Full bredde på felt 'mål for behandlingen' på medisinsk behandling

- src/felles-komponenter/ekspanderbar-linje/EkspanderbarLinjeBase.module.less
- src/moduler/aktivitet/visning/avtalt-container/AvtaltContainerNy.tsx
- src/moduler/aktivitet/visning/avtalt-container/ForhaandsorienteringsVisningsLinje.tsx
- src/moduler/aktivitet/visning/avtalt-container/SattTilAvtaltVisning.tsx
- src/moduler/aktivitet/visning/avtalt-container/aktivitet/AvtaltForm.module.less
- src/moduler/aktivitet/visning/endre-linje/endre-linje.module.less
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/Forhaandsorienteringsvisning.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/LestDatoVisning.module.less
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/LestDatoVisning.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/LestKnapp.tsx
Småting fikset sammen med Linn:
- Småfiks med luft
- Fikse en stillekkasje
- Fiks av typen tekst brukt på lestdatoen
- Legge til spinner på knapp etter at man har trykket på lest-knappen
- Bruke samme konstant som i container for å sjekke om det er en arenaaktivitet
> Småfiks på forhåndsorienteringsflyten

- package-lock.json
- package.json
- src/felles-komponenter/skjema/datovelger/utils.ts
- src/felles-komponenter/skjema/input/Checkbox.tsx
- src/felles-komponenter/skjema/input/Input.tsx
- src/felles-komponenter/skjema/input/Radio.tsx
- src/felles-komponenter/skjema/input/Select.tsx
- src/felles-komponenter/skjema/input/Textarea.tsx
- src/moduler/aktivitet/aktivitet-forms/behandling-gammel/validate.js
- src/moduler/aktivitet/aktivitet-forms/behandling/MedisinskBehandlingForm.tsx
- src/moduler/aktivitet/aktivitet-forms/egen/AktivitetEgenForm.jsx
- src/moduler/aktivitet/aktivitet-forms/egen/validate.js
- src/moduler/aktivitet/aktivitet-forms/ijobb/AktivitetIjobbForm.jsx
- src/moduler/aktivitet/aktivitet-forms/ijobb/validate.js
- src/moduler/aktivitet/aktivitet-forms/mote/validate.js
- src/moduler/aktivitet/aktivitet-forms/samtalereferat/validate.js
- src/moduler/aktivitet/aktivitet-forms/sokeavtale/AktivitetSokeavtaleForm.jsx
- src/moduler/aktivitet/aktivitet-forms/sokeavtale/validate.js
- src/moduler/aktivitet/aktivitet-forms/stilling/AktivitetStillingForm.jsx
- src/moduler/aktivitet/aktivitet-forms/stilling/validate.js
- src/moduler/aktivitet/aktivitet-forms/validate.js
- src/moduler/aktivitet/visning/avtalt-container-gammel/AvtaltForm.tsx
- src/moduler/aktivitet/visning/avtalt-container/aktivitet/AvtaltForm.tsx
- src/moduler/aktivitet/visning/avtalt-container/arena-aktivitet/ForhaandsorienteringForm.tsx
- src/moduler/aktivitet/visning/etikett-oppdatering/StillingEtikettForm.tsx
- src/moduler/mal/MalForm.tsx
- src/moduler/utskrift/printMelding.tsx
- src/moduler/utskrift/velgPlan/velgPlanUtskriftForm.tsx
På grunn av oppgradering av react, trenger vi å løfte versjonen på dette biblioteket. Det har vært en del breaking changes som fører til endringer i vår kode:
* strengere typing for useFormState()
* valideringsfunksjoner må returnere undefined, og ikke null ved validering ok
* ny funksjon setValue på FieldState og FormState må innkorporeres i våre custom inputkomponenter
Fikk veldig god hjelp av Nicklas Utgaard for å finne ut hva som måtte gjøres.
> Migrere use-formstate til ny versjon

- src/moduler/aktivitet/aktivitet-versjoner/aktivitet-versjoner-reducer.js
Når historikk-komponenten er åpen, forventer vi at den oppdateres dynamisk når aktiviteten endres.
https://trello.com/c/6DItXtBo
> Historikkvindu skal oppdateres ved fho lest og fho bekreft

- src/moduler/aktivitet/aktivitetlisteSelector.ts
Slik det var vil fullfør/avbryt med drag and drop ikke virke når arena er nede.
Filter vil heller ikke virke, og ikke utskriftsdialogen.
Sjekken av arenadata er tatt bort fra disse funksjonene.
https://trello.com/c/cGiTNo9d
> Dropper sjekk av om arenadata er lastet ved fullfør, avbryt, filter og print

- src/moduler/aktivitet/visning/hjelpekomponenter/VarslingBoks.tsx
https://trello.com/c/LXYCXugc
Varselet blir borte dersom varsel sendes til bruker.
Lurer på hvorfor dette varselet kun vises for aktivitetstype møte og ikke andre avtalte aktiviteter?
> Vaslingsboks til saksbehandler fjernes ved varsel sendt til bruker

- src/datatypes/aktivitetTypes.ts
- src/index.less
- src/moduler/aktivitet/ulest-markering/UlestMarkering.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/AktivitetinformasjonVisning.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/CustomAlertstripe.module.less
- src/moduler/aktivitet/visning/hjelpekomponenter/CustomAlertstripe.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/MeldInteresseForStilling.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/MeldInteresseForStillingen.module.less
- src/moduler/aktivitet/visning/status-oppdatering/oppdater-aktivitet-status.tsx
* Flytter aktivitetskort basert på hva man angir som svar på spm om å dele cv. Bruker nå samme funksjon som den som vanligvis flytter aktivitetskort og medfølgende metrikker
* Flytter ut custom "overskrift" alertstripe som benyttes av både ulestmarkering og som overskrift i denne komponenten. De er like utenom luft mellom ikon og tekst
* Benytter predefinerte konstanter til aktivitetstatus type for å gjøre det mer typesikkert fram til alt som benytter typen er i ts.
Visning av svar som er angitt er fortsatt ikke implementert
> Flytte aktivitet utifra svar på dele cv spm

- src/moduler/aktivitet/ulest-markering/UlestMarkering.module.less
- src/moduler/aktivitet/ulest-markering/UlestMarkering.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/CustomAlertstripe.module.less
- src/moduler/aktivitet/visning/hjelpekomponenter/CustomAlertstripe.tsx
for at styling ikke skal bli overstyrt i fss.
Fungerer allerede med !important styling men gjør forsøk på endring for å unngå det
> Styler VarselIkon isteden for tekst i CustomAlertstripe isteden for å bruke !important i stylingen

- src/datatypes/aktivitetTypes.ts
- src/felles-komponenter/ekspanderbar-linje/EkspanderbarLinjeBase.tsx
- src/mocks/aktivitet.js
- src/moduler/aktivitet/visning/AktivitetvisningModal.tsx
- src/moduler/aktivitet/visning/avtalt-container/utilsForhaandsorientering.ts
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/Forhaandsorienteringsvisning.tsx
- src/moduler/aktivitet/visning/hjelpekomponenter/forhaandsorientering/LestDatoVisning.tsx
- src/moduler/utskrift/print/aktiviteter/AktivitetPrint.tsx
- Ny popup hvis man ikke markerer FHO som lest før man lukker aktiviteten
- Fikse bug som gjorde at lestdato ikke lenger viste/oppdaterte seg riktig
- Fikse bug som gjorde at tittelen for streng beskjed ikke viste i åpen tilstand
> Strenge beskjeder: ny popup + bugfiks

- src/felles-komponenter/skjema/datovelger/utils.ts
- src/moduler/aktivitet/aktivitet-forms/mote/MoteAktivitetForm.tsx
- src/moduler/aktivitet/aktivitet-forms/mote/mote-aktivitet-form.test.js
- src/moduler/aktivitet/aktivitet-forms/mote/validate.ts
* Ny møtevalidator for hvordan datoer for møter skal valideres
* Ny fellesvalidator som gir valideringsfeil når datoen er tidligere enn dagens dato
* Fjerner ubrukte parametre fra validering
* Oppdaterer gammel test som opprettet møte på fast dato i fortid
* Ny test for at møtedato i fortid gir valideringsvarsel
> Valideringsfeil når møte blir satt opp tidligere enn samme dag

- src/app.js
- src/history.js
- src/hovedside/Hovedside.tsx
- src/index.js
- src/moduler/aktivitet/aktivitet-kort/Aktivitetskort.tsx
- src/routes.js
- src/routes.ts
Routing with `replaceState` does not trigger a react-router navigation. There is already an event we can use to trigger the navigation with includes aktivitetId
> Fix routing bug when linking from Dialog

- src/utils/avtaltResolver.ts
en "avtalt med nav"-aktivitet ble ikke oppdatert med nye verdier pga. feil i custom resolveren vår (de nye verdiene ble ikke returnert som forventet). dette skal fikse det
> fiks avtalt resolver bug

- src/felles-komponenter/modal/Modal.tsx
- src/moduler/aktivitet/avslutt/AvbrytAktivitet.tsx
- src/moduler/aktivitet/avslutt/FullforAktivitet.tsx
- src/moduler/aktivitet/ny-aktivitet/LeggTilForm.tsx
- src/moduler/aktivitet/ny-aktivitet/NyAktivitetForm.tsx
- src/moduler/aktivitet/rediger/EndreAktivitet.tsx
- src/moduler/aktivitet/visning/AktivitetvisningModal.tsx
- src/moduler/informasjon/informasjon-modal.tsx
- src/moduler/mal/mal-modal.tsx
- src/moduler/tilgang/tilgang-selector.ts
url-ble feil når man lukket modaler med Esc-knapp istedetfor å trykke på krysset. Løsningen ble å flytte ut navigering til onClose der det gir mening. onClose blir alltid kalt når man lukker modalen, det blir ikke onRequestClose (ref bug-beskrivelse i aksel kanalen)
> Legg til onClose på alle modaler
